apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deployment
  namespace: lesson15
  labels:
    app: goapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
        - name: web
          image: imm0bilize/practice-k8s:latest
          ports:
            - containerPort: 8080